### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by georgiazhang** [prateekiiest/Student-Group-Activity-Recognition#1]
Thanks for your great work!
Can you please show me how to run the code?

**Comment by prateekiiest** [comment]
@georgiazhang 
You need to open a new Jupyter Notebook.
You can copy the code there and run it. 
I will shortly upload a code editor if possible where you can run them.

**Comment by georgiazhang** [comment]
thank you.
I have tried, but i couldn't find the  files like "project26.txt",etc.

**Comment by prateekiiest** [comment]
Ok, I think I haven't uploaded the text files like 'project30.txt' and others. 
I will upload them shortly.
Thanks for pointing it out.

**Comment by georgiazhang** [comment]
Thank you , looking forward to your updating.

**Comment by prateekiiest** [comment]
@georgiazhang 
Sorry for the late upload.
Due to classes I could not upload it earlier.
You can find the files here
https://github.com/prateekiiest/Student-Group-Activity-Recognition/tree/master/DataFiles

Let me know if there are any other bugs you might find. :)

**Comment by prateekiiest** [comment]
Oh, there are some files about the wifi data, under JC (you might see that in the Docs).
Its about 35,700 files in total.
Hence I can't upload such a huge list there.
I will upload some 2-3 sample files .

**Comment by georgiazhang** [comment]
Thanks,  i can run the IntershipDocs. My question is that the dataset you used in the Docs is not same as StudentLife dataset?right?

**Comment by prateekiiest** [comment]
Yes its a part of the Student Life Data Set, only the wifi values and location values and gpa values of students.
You can collect it from the Darmouth College Website

**Comment by prateekiiest** [comment]
Let me know if you face any further issue
